### ISSUE TITLE
Support scheduled/unattended runs

### ISSUE THREAD

**Issue by jorsmatthys** [NickLiffen/ghas-enablement#52]
We are trying to run this tool from a GitHub runner (macOS), on a schedule. 
Currently this doesn't work completely yet because the git commands that are used to commit the codeql file rely on local ssh configuration or user prompts. We would like it if this part could also make use of the PAT / GitHub App auth. 

I have tested a change for this locally which seems to work and added commands for wsl/linux, . I still need to figure out how to ensure that the token will not be shown in the output of the script. (currently it prints all the commands showing the secret). 

Do you think this can be added? @NickLiffen 
If so I will clean it up a bit and create a pull request for you to review/refactor.
Also do you think it should always commit the file through the app auth, or should it be an option in the .env file ? 

Kind regards,
Jors

**Comment by jorsmatthys** [comment]
Apparently, GitHub Actions is smart enough to automatically mask the secret used to clone the repos on which pull-requests have to be created.
`
    command: 'git',
    args: [
      'clone',
      '***github.com/liantisit-github-automation-poc/hcl-repo.git'
    ],
`
So maybe it is fine not to do anything specific for this. If you run it locally it would not be a huge problem either. 
If it does need to be masked the easiest option as far as I see would be to disable the stdout logging of the git commands o

**Comment by NickLiffen** [comment]
Hey @jorsmatthys 👋 sorry for not responding to this 🙇 I have been a bit busy recently so firstly please accept my apologise 🙇 

> Apparently, GitHub Actions is smart enough to automatically mask the secret used to clone the repos on which pull-requests have to be created.

This was going to be my thought 💭 I don't think this is a problem to be honest because we should mask the token as shown above 👍 

> If so I will clean it up a bit and create a pull request for you to review/refactor.

I would love this ❤️ if you could update the `README.md` when you do it, it would be amazing :) I would defiantly appreciate this PR 🙇 

> Also do you think it should always commit the file through the app auth, or should it be an option in the .env file ?

I think it should commit with either the PAT or GitHub App auth, whatever one is set 👍 If they set the github app auth, it should push and commit via that, if they have set the PAT, it should commit with that 👍 

just to keep it consistent :) 

Thanks for your help 🙇 

> If you run it locally it would not be a huge problem either.

Agreed 👍

**Comment by jorsmatthys** [comment]
Hi again @NickLiffen. 
Thanks for the positive feedback :) ! I created a pr. Let me know if you still want something changed.

**Comment by NickLiffen** [comment]
Conversation now in #62
